### ISSUE TITLE
Django 2.x support

### ISSUE THREAD

**Issue by frague59** [tutorcruncher/django-bootstrap3-datetimepicker#19]
Hi, 

New django 2.0 / 2.1 uses a new parameters "renderer=None" in the on widget rendering 

This parameter is not in the DateTimePicker.render() method, so I have an exception:
```
render() got an unexpected keyword argument 'renderer'
```
Could it be added ?

Thanks !

**Comment by samuelcolvin** [comment]
Pull request welcome.
