### ISSUE TITLE
'DatePicker' object has no attribute 'conv_datetime_format_js2py'

### ISSUE THREAD

**Issue by cjshaw1976** [tutorcruncher/django-bootstrap3-datetimepicker#21]
Good day, I encounted the error **'DatePicker' object has no attribute 'conv_datetime_format_js2py'**. On line 75, I think you need to change **format = self.conv_datetime_format_js2py(options.get('format'))** to **format = self.conv_date_format_js2py(options.get('format'))**

**Comment by cjshaw1976** [comment]
My bad. I was trying to put the issue on https://github.com/jckw/django-bootstrap-datepicker-widget, and for some reason it came here. Lucky in a way, that I have found this project to work well and am using it instead.

**Comment by Hudeh** [comment]
hello how were you able to resolve the issue sir
