### ISSUE TITLE
'ddd' in format broken

### ISSUE THREAD

**Issue by drvid** [tutorcruncher/django-bootstrap3-datetimepicker#3]
According to the JS docs I should be able to use 'ddd' to get the day of week 3 letter abbreviation.

This works as expected when setting a date with DateTimePicker, but when I try to load a bound ModelForm DateTimeField using this format in the widget options the form field is rendered empty!

**Comment by samuelcolvin** [comment]
Off the top of my head I have absolutely no idea.

I'll try and have a look into it in a couple of days.

@tomhamiltonstubber can you remind me about this.

**Comment by drvid** [comment]
so also when using `'format': 'MMM DD, YYYY h:mm a'`
I have the same problem, rendering of the field appears empty as if moment.js can't parse it.
Further inspection of the html element value shows it's rendering `value="May 06, 2016 h:39 AM"`
Which at least explains why it can't be parsed in JS.
I also tried the `'ddd MMM DD, YYYY h:mm a'` once more and found the same value rendered as above. Hope this helps!

**Comment by samuelcolvin** [comment]
closing this as we haven't had any problems.
