### ISSUE TITLE
No module named bootstrap3_datetime.widgets

### ISSUE THREAD

**Issue by wlopz** [tutorcruncher/django-bootstrap3-datetimepicker#4]
I am trying to get your DatePicker to work on my template but I am getting the error: **No module named bootstrap3_datetime.widgets**

I tried to add `'bootstrap3_datetime'` to my `INSTALLED_APPS` like in `nkunihiko` widget since you forked it from there but no success.

Would appreciate your help

This is what I have in my `models.py`:

```
class Production(TimeStampedModel):

        #Some other code.....

        scheduled_date = models.DateTimeField(null=True, blank=True)
        fully_produced_date = models.DateTimeField(null=True, blank=True)
```

In my `forms_schedule.py`:

```
from django import forms

from bootstrap3_datetime.widgets import DateTimePicker

from .models import Production



class ScheduleForm(forms.ModelForm):

    class Meta:

        model = Production
        fields = ['scheduled_date', 'fully_produced_date']
        widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm", "pickSeconds": False})

    def clean_scheduled_date(self):
        scheduled_date = self.cleaned_data.get('scheduled_date')

        return scheduled_date

    def clean_fully_produced_date(self):
        fully_produced_date = self.cleaned_data.get('fully_produced_date')

        return fully_produced_date
```

`views.py`

```
def episodeschedule(request):

    title = 'Podcast'
    title_align_center = True
    subtitle = 'Setup | Add Episode'
    subtitle_align_center = True
    form = ScheduleForm(request.POST or None)
    context = {
        "title": title,
        "subtitle": subtitle,
        "form": form
    }

    if form.is_valid():

        instance = form.save(commit=False)

        scheduled_date = form.cleaned_data.get("scheduled_date")
        fully_produced_date = form.cleaned_data.get("fully_produced_date")

        instance.scheduled_date = scheduled_date
        instance.fully_produced_date = fully_produced_date

        instance.user = request.user

        instance.save()

        return render(request, "forms_schedule.html", context)

    else:

            return render(request, "forms_schedule.html", context)
```

And `forms_schedule.html`:

```
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="progress">
  <div class="progress-bar progress-bar-striped progress-bar-success active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
    <span class="sr-only">100% Complete</span>
  </div>
</div>

<div class="panel panel-default box-shadow--16dp col-sm-6 col-sm-offset-3">
<div class="panel-body">

<div class='row'>
<div class='col-sm-12'>

{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}<!-- : {{ get.clientsetup.company_name }} --></h1>
{% endif %}
{% if subtitle %}
<h3 class='{% if subtitle_align_center %}text-align-center{% endif %}'>{{ subtitle }}</h4>
{% endif %}

<h5>Schedule</h5>

<form method='POST' action=''>{% csrf_token %}
{{ form|crispy }}

<!-- <input type='text' class="form-control" id='datetimepicker4' /> -->

<hr/>

<input class='btn btn-info box-shadow--6dp' type='submit' value='Save' />
<p>
<p>
<a class="btn btn-primary box-shadow--6dp" href="{% url 'dashboard' %}" role="button"><i class="fa fa-upload" aria-hidden="true"></i>&nbsp SCHEDULE EPISODE</a>

</form>
</div>
</div>

</div>
</div>

{% endblock %}
```

**Comment by wlopz** [comment]
Nvm, got it solved.

**Comment by samuelcolvin** [comment]
Glad to hear you got it solved. Sorry not to be more help.
On 11 Jun 2016 6:04 a.m., "Wil" notifications@github.com wrote:

Nvm, got it solved.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/tutorcruncher/django-bootstrap3-datetimepicker/issues/4#issuecomment-225337246,
or mute the thread
https://github.com/notifications/unsubscribe/AD2jGYj27B9Yc1_LReu8lPTHPcO1K4Noks5qKkHFgaJpZM4IzX-t
.

**Comment by wlopz** [comment]
Its ok, but now I am having another issue. The only thing I changed was inside my `forms_schedule.py`:

I removed the following snippet:

```
       widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm", "pickSeconds": False})

    def clean_scheduled_date(self):
        scheduled_date = self.cleaned_data.get('scheduled_date')

        return scheduled_date
```

And added this:

```
scheduled_date = forms.DateTimeField(required=False, widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm", "pickSeconds": False}))
```

Now I am getting the minimum setup with the Schedule glyphicon on the right but when I try to click on the field or the right button, its not show no datepicker or time.

**Comment by wlopz** [comment]
By the way, I had to get your `widgets.py` and copy all the code and put it in my project to make it work since that was causing me the issue of not locating the module.

**Comment by samuelcolvin** [comment]
Weird is not finding the module. Which version of python are you using? How
are you installing the package?

We're using this in production and it's working fine.

**Comment by samuelcolvin** [comment]
Is it a public project? If so I'll try and have a look at what's going on
next week. Currently away from my computer.

**Comment by wlopz** [comment]
Thanks for the help, I am using version `2.7.10` in my mac and inside Vagrant Virtual Machine, its using version `2.7.6`. I installed the package using `sudo pip install django-bootstrap3-datetimepicker-2`

Let me know when you are back at your computer and I will push the project into the feature branch that I am currently working so you can check it out.

**Comment by wlopz** [comment]
Forgot to mention that my django version is `1.9`

**Comment by wlopz** [comment]
Sent you an e-mail (jrlopez@gmail.com) with repo link.
`widgets.py` is in the `producer` folder. Javascript is inside `static` folder, Javascript header is in `templates/pod_funnel/javascript.html`, Template that I am currently trying to implement the datetime picker is in `templates/pod_funnel/forms-schedule.html` and the view is in `views/forms/schedule.py`
