### ISSUE TITLE
Documentation on grablib

### ISSUE THREAD

**Issue by LegoStormtroopr** [tutorcruncher/django-bootstrap3-datetimepicker#6]
Firstly, really appreciate you taking this on.

It seems one of the big changes from django-bootstrap3-datetimepicker is the exclusion of the static files. The Readme suggests using `grablib`,  but it would good if you could include a barebones instruction or `grablib.yml` file to make the transition easier.

**Comment by samuelcolvin** [comment]
related to #7, I'll answer there.
